# https://docs.docker.com/compose/compose-file/
# https://docs.docker.com/compose/compose-file/03-compose-file/

services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
